# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161016_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='paypal',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='private_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='public_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
