# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 01:39
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_project_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
